### ISSUE TITLE
当Qv2ray重启时，cgproxy的日志中会出现不致命报错

### ISSUE THREAD

**Issue by sixg0000d** [springzfx/cgproxy#13]
### 错误现象
当 cgproxy 作为服务自启时，每次重启Qv2ray中的节点，会出现一次该报错：
https://github.com/springzfx/cgproxy/blob/8ea40623842338d1defa05473238d283aa2972f4/src/cgroup_attach.cpp#L81
然后出现两行正常的 `info: execsnoop; noproxy: **** /usr/bin/v2ray` ，其中最后一行的 pid 与正在运行的 v2ray 程序 pid 一致。

### 错误影响
对使用几乎没有影响

### 复现步骤
1. 启用 cgproxy 服务
2. 启动 Qv2ray
3. 在 Qv2ray 中双击现在正在使用的节点
4. `journalctl -u cgproxy -b 0` ，查看最新生成的日志

### 复现机率
约 90%

### 例外现象
如果 cgproxy 不是以 systemd 服务自启而是开机后 start 或手动运行，不会有该现象发生
也就是说：`systemctl restart cgproxy` ，现象消失。停止服务后手动执行 `sudo cgproxyd --execsnoop` ，不会有错误日志产生。

### 使用 cgproxy 版本及安装来源
安装来源：编译安装
使用分支： 55d67f4799133577c8745c78292c0b8d88319999

### 相关软件版本
Linux 发行版：Fedora release 32 (Thirty Two)
内核版本：5.7.11-200.fc32.x86_64
Qv2ray版本：2.6.2:5800（来自 OBS）

### 配置文件

> /etc/cgproxy/config.json

```
{
    "comment":"For usage, see https://github.com/springzfx/cgproxy",

    "port": 60080,
    "program_noproxy": ["v2ray", "qv2ray"],
    "program_proxy": [],
    "cgroup_noproxy": ["/system.slice/v2ray.service"],
    "cgroup_proxy": ["/"],
    "enable_gateway": false,
    "enable_dns": true,
    "enable_udp": true,
    "enable_tcp": true,
    "enable_ipv4": true,
    "enable_ipv6": true,
    "table": 10007,
    "fwmark": 39283
}

```

> Qv2ray 入站设置

![2020-08-07 07-25-33 的屏幕截图](https://user-images.githubusercontent.com/17105863/89592448-3895a980-d87f-11ea-8f5a-eead2d2a2b87.png)

### 问题补充
1. To be continued

**Comment by springzfx** [comment]
archlinux下cgproxy-git没有复现这个问题

**Comment by sixg0000d** [comment]
找到问题根源了，Qv2ray 在连接节点时共会调用3次 v2ray 程序，其中第一次基本等同于命令 `v2ray --version` 。
所以我测试了，在完全不使用任何 v2ray / Qv2ray 进程的情况下，反复执行命令 `v2ray --version` ，从第二次开始，能够 100% 复现该报错。
当然，既然是 `v2ray --version` 才会产生，所以这个 error 绝对不会影响任何正常使用。

同样地，我将其他有快速输出版本号的命令的程序写入不代理程序，例如
```json
{
    "program_noproxy": ["v2ray", "qv2ray", "/usr/lib64/firefox/firefox"]
}
```
执行 `firefox -v` 命令，亦能复现该报错。

~~目测是因为进程结束太快，导致 execsnoop 没有捕捉到进程产生的。（也就是和cgproxy没太大关系了）~~
不太清楚该 PID 是由 cgproxy 或者 execsnoop 负责捕捉？
**而且目前只有我的 Fedora 能够复现该错误。**

**Comment by sixg0000d** [comment]
我觉得这个错误可能不仅仅是会影响日志这么简单，因为刚才我试了能够瞬时产生输出并结束的 `curl` 命令亦能复现该错误。
**头疼的是目测 Archlinux 不会有该错误而目前只有我的 Fedora 能够复现该错误。**

**Comment by springzfx** [comment]
其实就是进程生命周期太短了，在移动cgroup时，它已经退出了

**Comment by springzfx** [comment]
https://github.com/springzfx/cgproxy/commit/b2d49eb6ca4e20e89f3628e2cd7c9a3423c2ee28 忽略了这类错误，不过仍会存在很小的概率会出现，这是正常现象

**Comment by sixg0000d** [comment]
在最新版，我测试的几种使用场景已不会触发该错误
