### ISSUE TITLE
how to support UDP with qv2ray

### ISSUE THREAD

**Issue by ajfpay** [springzfx/cgproxy#51]
I always use qv2ray with http or socks and setting on firefox proxy or gnome network same port qv2ray setting.
But the problem I can't video call or call with discord, I think qv2ray with xray not supported with UDP.

*edit
Change core to v2ray and everything is fine

**Comment by adwinb** [comment]
Your qv2ray log says it works fine with UDP.

Are you using discord in Firefox browser?  Browsers usually support socks/http proxy only.
Just remove firefox from your cgproxy config and enjoy global transparent proxy :)

**Comment by ajfpay** [comment]
thanks
