### ISSUE TITLE
希望可以增加 nft 支持

### ISSUE THREAD

**Issue by unknowndevQwQ** [springzfx/cgproxy#6]
就像标题说的那样
至于为什么需要支持 nft，我个人认为 nft 会让规则维护更方便

**Comment by springzfx** [comment]
*nft* still missing cgroup2 feature. So it won't be supported for now.

**Comment by unknowndevQwQ** [comment]
> _nft_ still missing cgroup2 feature. So it won't be supported for now.

现在 nft 可以使用 cgroup v2 了

**Comment by unknowndevQwQ** [comment]
@springzfx 劳烦重新打开这个问题，我将尝试为 cgproxy 添加 nftables 支持
